---
- name: installiert NTP
  apt: name=ntp state=present

- name: NTP Konfiguration hinterlegen
  template: src=ntpd.conf.j2 dest=/etc/ntpd.conf
  notify: restart ntp

- name: NTP Autostart aktivieren
  service: name=ntp enabled=true state=started
